# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py


language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  # PyPy versions
  - "pypy"
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
# command to run tests
script: 
  - pytest --doctest-modules --pep8 datafs,examples -v --cov datafs,examples --cov-report term-missing

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: delgadom
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: ClimateImpactLab/datafs
    condition: $TOXENV == py27

services: 
  - mongodb


after_success:
  - coveralls