language: python

python:
  - 2.7
  - pypy

env:
  global:
    DYNAMODB_URL: http://dynamodb:8000/
  matrix:
    - DATAFS_TEST_ENV=basic
    - DATAFS_TEST_ENV=xarray
    - DATAFS_TEST_ENV=conda

matrix:
  allow_failures:
    - python: pypy
      env: DATAFS_TEST_ENV=xarray
    - python: pypy
      env: DATAFS_TEST_ENV=conda


install:
  - if [[ "$DATAFS_TEST_ENV" == "xarray" ]] || [[ "$DATAFS_TEST_ENV" == "conda" ]]; then
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      export PATH="$HOME/miniconda2/bin:$PATH";
      hash -r;
      conda update --yes -q conda;
      conda config --set always_yes yes --set changeps1 no --set anaconda_upload no;
      conda info -a;

      conda install -q python=$TRAVIS_PYTHON_VERSION pip requests conda-build jinja2 anaconda-client;
      conda install -q h5py netCDF4 xarray dask numpy scipy pandas h5py hdf5 numba blaze scipy bottleneck dask;
    fi

  - if [[ "$DATAFS_TEST_ENV" == "conda" ]]; then
      conda update --yes -q conda;
      conda update --yes -q conda-build;
      conda build conda-recipe;
      conda install --use-local $PACKAGENAME;

    else
      python setup.py install;
      python -m pip install .;
      python -m pip install .[test];
      python -m pip install -r requirements.txt;
      python -m pip install -r requirements_test.txt;
      python -m pip install git+https://github.com/PyFilesystem/pyfilesystem#egg=0.5.5a1;
      python -m pip install coveralls;
      python -m pip install pytest-cov;
    fi

script:
  - export PATH=$HOME/miniconda/bin:$PATH
  - export PATH=$HOME/miniconda2/bin:$PATH
  - export PATH=$HOME/miniconda3/bin:$PATH
  - python -m pytest ./datafs ./tests ./docs --cov=datafs --cov=examples --cov=docs --doctest-modules --cov-report term-missing

services:
  - mongodb
  - dynamodb
  - docker

before_install:
  - docker pull tray/dynamodb-local
  - docker run -d -p 8000:8000 tray/dynamodb-local -inMemory -port 8000

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - coverage combine
  - coveralls

  # Change permissions for Anaconda deployment script
  - chmod +x ./deploy_anaconda.sh

deploy:

  # Deploy to pypi
  - provider: pypi
    user: delgadom
    password:
      secure: Jw4AqKuQcVpK9nsLZu/chk91cLGZxdwTugewhQlaEp5k1Hyx6HxvJMg5LFg4cFzfzRibmOtatWJUDy9XA3q7OhDNwKjd2UxCflOpB/Sb3jsgUWnEnGOgr8bDbnfRUW40zZf4vheKhSGif5hf3HqtnPMe41vtLy8QzTQSMl7FHgLI0eW+6sXErzKdDVmkcNGFhjClm7/yWJRPxNxFsJv2ofXMFkdN97eaN8gOiNKteB0JRHsKiAvH/y8nHKO/R/f3GwAyXw+WlkxoD0iMYyAUy+CTU1U83Kphwym1y2xkh6KGJnyKMiOm7bSWqomHRcHD5vCj8Qlxz5LD+Xpy/CIRe3tw5YmDJDrpTAEQLJgH5h2ers6H7+uk5VPdBL8O/L+Vk2yKAt0F0nWw9nObiGWCUx3efuikqyEDZkpiGkDgFszIFeLpvd1TFSM0AnQNhhof3KDaFSkTGc4cuYPKbVQCAC0wevZPExKj5f6djPkyl5SaoAOGbHfuKuLsHbssX8IBOU193r8c/K03rjDTtcwvkT73uKE2II9Rfo8R8drqH/kznr8Kq1wUEKGh/A4uretZlr2dw051qi6qxgEgUKoQNfuIhP+5KBm7Zp2jIdG3Nqi4iP9zpH4+Kjwvhl6hn9Kx5SDwxVwbnS5A9P7I6L32QyZbc5VJSs2RaiKeG5h8o7I=
    on:
      branch: master
      distributions: sdist bdist_wheel
      repo: ClimateImpactLab/DataFS

  # Deploy to Anaconda.org
  - provider: script
    script: ./deploy_anaconda.sh
    # on:
    #   branch: master

    skip_cleanup: true